# Generated by Django 4.2.7 on 2023-11-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_merchant_id_order_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_intent',
            new_name='merchant_id',
        ),
    ]
